from .relations import RELATIONS, QUANTITY
from .relations import TEMPLATE_NAME, PART_NAME, WEAPON_NAME, WEAPON_SLOT_NAME, COLOR_NAME
from .relations import TEMPLATE_PARTS_JOINT, WEAPON_PARTS_JOINT, WEAPON_SLOT_WEAPONS_JOINT, TEMPLATE_WEAPON_SLOTS_JOINT
from .relations import TEMPLATE_MINIFIGURE_PART_TABLE, TEMPLATE_MINIFIGURE_WEAPON_SLOT_TABLE, WEAPON_SLOT_WEAPON_TABLE, WEAPON_PART_TABLE, COLOR_TABLE

from .tables import LEGO_PART_TABLE, TEMPLATE_MINIFIGURE_TABLE, ACTUAL_MINIFIGURE_TABLE, WEAPON_SLOT_TABLE, WEAPON_TABLE
from .tables import PRIMARY_KEY_NAME