from .web_managers import LegoPartWebManager, WeaponWebManager, WeaponSlotWebManager, TemplateMinifigureWebManager, ActualMinifigureWebManager
from .web_models import WebTable
from .base_web_managers import BaseWebManager